### ISSUE TITLE
small items: check console errors

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#52]

**Comment by rstan-dev** [comment]
xhr.js:187 
        
        
       POST https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu105.gitpod.io/dj-rest-auth/token/refresh/ 401 (Unauthorized)
dispatchXhrRequest @ xhr.js:187
xhrAdapter @ xhr.js:13
dispatchRequest @ dispatchRequest.js:53
request @ Axios.js:108
Axios.<computed> @ Axios.js:140
wrap @ bind.js:9
(anonymous) @ CurrentUserContext.js:58
Promise.then (async)
request @ Axios.js:114
Axios.<computed> @ Axios.js:129
wrap @ bind.js:9
handleMount @ CurrentUserContext.js:20
(anonymous) @ CurrentUserContext.js:29
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
xhr.js:187 
        
        
       GET https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu105.gitpod.io/dj-rest-auth/user/ 401 (Unauthorized)
dispatchXhrRequest @ xhr.js:187
xhrAdapter @ xhr.js:13
dispatchRequest @ dispatchRequest.js:53
request @ Axios.js:108
wrap @ bind.js:9
(anonymous) @ CurrentUserContext.js:67
Promise.then (async)
request @ Axios.js:114
Axios.<computed> @ Axios.js:129
wrap @ bind.js:9
handleMount @ CurrentUserContext.js:20
(anonymous) @ CurrentUserContext.js:29
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157

CurrentUserContext.js:23 Error: Request failed with status code 401
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:54:1)
