### ISSUE TITLE
small items check ref warning for overlay trigger in JobCard

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#69]
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of RefHolder which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at span
    at RefHolder (https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu105.gitpod.io/static/js/vendors~main.chunk.js:15547:29)
    at OverlayTrigger (https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu105.gitpod.io/static/js/vendors~main.chunk.js:15580:22)
    at a

**Comment by rstan-dev** [comment]
Seems to be an issue with the bootstrap vendor - leaving this and addressing this a bug unresolved
