### ISSUE TITLE
small items: accordian, displaying edit and chat icons

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#90]
- [x] Add accordian to All Jobs Page
- [x] Display Chat and Edit in accordian header if there are chats and if user can edit - conditional
- [x] Add accordian to Invoices

**Comment by rstan-dev** [comment]
See warning in JobCard and InvoiceCard due to React Bootstrap 4 Accordian

index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at Transition (https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu106.gitpod.io/static/js/vendors~main.chunk.js:20950:30)
    at https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu106.gitpod.io/static/js/vendors~main.chunk.js:12453:22
    at https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu106.gitpod.io/static/js/vendors~main.chunk.js:10966:23
    at div
    at https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu106.gitpod.io/static/js/vendors~main.chunk.js:11604:23
    at div
    at https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu106.gitpod.io/static/js/vendors~main.chunk.js:10913:96
    at div
    at div
    at div
    at div
    at div
    at JobCard (https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu106.gitpod.io/static/js/main.chunk.js:8408:5)
